import React from "react";
import HeaderPageBlock from "../../../../blocks/HeaderPageBlock";
import headerImg from "./../../../../img/news/2-1.jpeg";
import PicAndText from "../../../../blocks/PicAndText";
import aboutUsPhoto from "./../../../../img/about-us-photo.png"
import vanyaImg from "./../../../../img/pages/ohua/vanya.png"
import mishaImg from "./../../../../img/pages/ohua/misha.png"
import andryImg from "./../../../../img/pages/ohua/andry.jpg"
import jeniaImg from "./../../../../img/pages/ohua/jenia.jpg"
import stasImg from "./../../../../img/pages/ohua/stas.png"
import TextAndPic from "../../../../blocks/TextAndPic";
const ProjectOhua = () => {

    return (
        <div className="Ohua">
            <HeaderPageBlock title={<h1 className="Ohua-title">Orphans Hope Ukraine</h1>} />
            <div className="Ohua-wrap">
                <div className="Ohua-wrap-content">
                    <div className="Ohua-wrap-header-image">
                        <img src={headerImg} alt="OH Mayak" />
                    </div>
                    <div className="Ohua-wrap-content-title">
                        <h2>OH work in Ukraine and Crimea</h2>
                    </div>
                    <div className="Ohua-wrap-content-p">
                        <p>We started our OH work in Ukraine and Crimea back in 2002 and have been working here for over 20 years. Dmytro Malashko and Volodymyr Tverdenko were the directors and managers of this NGO there all these years. Liliya Malashko, Olesya Prytchenko, Tanya Fedoseeva|Shanina, Pavlo Melnykov and many others really helped us on a permanent basis. The main work was carried out in Crimea from 2000 to 2014 (15 years) and in Kyiv from 2015 to 2024 - it is already the 10th year. Mainly it was social work to overcome orphanhood on the streets of Crimea (2000-2001) and later from 2002 in boarding schools and orphanages all over Crimea. Also we serve in different children's centers, vulnerable families and internally displaced families as prevention work. Later it continued in Kyiv. From 2002 to 2010, it was mainly volunteer work in boarding schools and assistance to Ukrainian orphans to live in foster families at the churches of Crimea, Ukraine and the whole world. We made a lot of educational and preparatory activities for the Christian community related to the problem of orphanhood and professional social work regarding its solution. And since 2011, it was also the work of collaboration and training mentors for 100 orphaned kids and teenagers from Crimean orphanages, foster parents and employees of NGOs and churches in Crimea, and coordination of these activities until the end of 2014. We also had a support program for young people - graduates of boarding schools and foster families - student mini-grants for them and summer & winter resting activities. A lot of short-term missionary teams from the USA, Canada, and Europe came to Crimea to help and support our work with orphans. We have been building a sustainable model of smart social Charity with children and families and doing a lot of research and practical work with them. Steve Cassidy and his partners and staff, various volunteers and missionaries helped us a lot all these years from the US side. During this time, we purchased an office and Youth Center, a house White Lion for a foster family to live in. We had a good summer camp spot of land for nearly 100 teens on the Black Sea coast from 2000 to 2014 and made a lot of good activities there. We also distributed a lot of humanitarian aid to people around us and we had quite a large circle of vulnerable kids & teens who knew and trust us. Over the years, we have managed to influence thousands of children and teenagers, as well as hundreds of families and young people in Crimea. And we made really deep & holistic work for them.  </p>
                        <p>In 2015, we had to leave Crimea and move to Kyiv due to the annexation of our land by Russians and the war unleashed by Putin in Ukraine. This war has been going on for the tenth year. Many families and children suffered and left Crimea, Donbas and then Ukraine during this period. In Kyiv on a permanent basis we worked with two boarding schools, several children's centers and Family Clubs for vulnerable families and IDP youth on the right and left banks of the city. We involved a lot of volunteers from various churches, NGOs and universities of Kyiv and all over Ukraine, also other parts of the world to serve Ukrainian orphans. During all this time our focus was on more than 100 kids and teens on permanent support and about 1,000 children in general coverage, mainly children from at-risk families, whose parents we also actively worked with, as well as more than 100 orphans with status. We began to teach people about competent volunteer work with orphans: prevention and intervention, collaboration and anti-burnout, as well as the Case Management approach and Therapy based on relationships intervention (TBRI) from Texas Christian University. All these past 10 years we have interacted a lot and helped various partners throughout Ukraine in working with orphaned children, participated in various round tables, trainings, conferences, as well as in the bicycle race and movement "Ukraine without orphans", as well as the nationwide initiative Orphans Sunday - the Day of Prayer for orphans: large-scale informing of Ukrainian society about the problems of orphans. In Kyiv we also were able to influence thousands of children and hundreds of families of IDPs, as well as foster families and adoptive parents. We have a lot of stories and testimonies of changed lives. We have also implemented and adapted various projects, programs and studies to assess their needs and to help and support children and families in crises. And we also trained and accompanied people from churches and NGOs in their professional and integral social, pedagogical and psychological work, we learned with them sustainable management and modern approaches in working with children, youth and families. We see the importance of contributing to the young generation of Ukraine: in their awareness, values, spirituality, new approaches, skills, relationships and quality of their communication, as well as in their involvement in civil society processes.</p>

                    </div>
                    <PicAndText title={<h2>4 years ago</h2>} text={<p>
                        In 2020, the Covid-19 pandemic began, and access to residential schools was limited for volunteers because of that. The maximum number of children was returned to their families in Kyiv and throughout Ukraine. If you look at it in context, the vulnerable families were mainly poor families who found themselves in difficult life circumstances and for various reasons could not take care of their children and sent them to boarding schools so that the child was at least fed and warm. Many of these families drunk a lot and lead an anti-social lifestyle. And it turns out that the state returned these children to their biological families. Also the first year of the pandemic was a year of mass unemployment and isolation. And that's why our mission was to help and support such families overcome the crisis and ensure that children remain in their families. From 2020 to 2022 we were able to help many families with children and support them in such a difficult period.
                    </p>} url={aboutUsPhoto} />
                    <div className="Ohua-wrap-content-p">
                        <p>Then after russian troops left the Kyiv we went to the territories that were under occupation and helped families with children and orphans. After the situation more or less stabilized, we started various clubs of support and development for children and teenagers, renewed training in IT courses for teenagers and graduates of boarding schools. In total, in 2022, we helped about 5,000 people with children, more than 150 of them were orphans.</p>
                        <p>In 2023 the war against “soviet russians” is still going on in Ukraine. And we have resumed our trips to Mayak boarding school 1-3 times a week where during the year we were able to take care of 100 children teaching them social skills, robotics and simple ways of communication and hugs. Children are very happy when we come to them and wait for us. We are stable and constant volunteers and they can rely on us as mentors, we also understand that children need a family even more. Our partners and donors are important to us so we thank everyone who has helped and continues to do so together with us and we invite you to join our work in the future years. And we will try to share our news with you on our website. </p>
                        <p>As a result of our 20 years of Christian work in Ukraine are nearly 100 young people who really trust God: follow Him and go to different churches. Also 20 of our graduates got high education in different Universities and colleges. And 10 of our people got married already and some  of them even have their own kids and care for them. So we have a future generation of hope. </p>
                        <p>We would now like to tell you as an example the stories of two brothers and one of our permanent volunteer students Andrew who went with us for 5 years to the orphanage and also the stories of our other boys from the "Men's Club" in the Mayak Center of Kyiv.</p>
                    </div>
                    <div className="Ohua-wrap-content-title">
                        <h2>The story of Vanya and Misha</h2>
                    </div>
                    <div className="Ohua-wrap-content-col-two">
                        <div className="col first">
                            <img src={vanyaImg} alt="Vanya" />
                        </div>
                        <div className="col sec">
                            <img src={mishaImg} alt="Misha" />
                        </div>
                    </div>
                    <div className="Ohua-wrap-content-p">
                        <p>The heroes of our story from OHUA are Vanya and Misha</p>
                        <p>Vanya is 15 years old, studies in the 6th grade (he started his first grade only at 9 years old), Vanya also has slight problems with speech. Very kind, active, open, in some ways even naive and it is difficult for him to formulate his thoughts</p>
                        <p>Misha is 13 years old Vanya’s brother, studies also in the 6th grade with his brother, and started studying in the 1st grade at the age of 8. Misha says that he also had problems with speech and that’s why they went to school so late and the guys are worried about this. Misha is also very kind, responsible and sociable. And he is also the head of his group at the Center.</p>
                        <p>The guys helped each other a lot, protected each other and cared for each other. They lived with their mother in Kyiv, but their father was not with them.</p>
                        <p>Unfortunately, on February 24, 2022, russia attacked Ukraine and a huge number of bombs and missiles flew at us all in Kyiv. There was a lot of anxiety but their family managed to survive and adapt to the new realities of life. In the fall of 2022 russia began attacks on the energy system of Ukraine, as a result of which there was no electricity for days and people began to use alternative sources for indoor lighting and cooking. Their family was no exception. It so happened that the mother lit a candle and did not notice how it fell and a fire started in the whole apartment. No one was injured, only the apartment was damaged and it was not a safe place for the children to live any more. These were very difficult consequences of the war for this family. </p>
                        <p>The social service arrived and removed Vanya and Misha from the family due to poor living conditions for the children, and their mother was told that when she restored the home, the children would be returned to her. Mom started the process of renovating the apartment, but there was a lack of money, no work and just small support from relatives and friends. Some neighbors began to help them both financially and physically.
In the meantime, the boys were sent to the Center of socio-psychological rehabilitation (like boarding school). The guys adapted quite quickly, went to school, play basketball in the sports section and go to programming and robotics courses. Misha, thanks to his leadership qualities, became a leader of the group of 15 teens at the Center. .
</p>
                        <p>At the moment, the guys have been away from home for almost a year. Now volunteers come to this center, and take care of them and teach them soft skills/life skills so that the children, after leaving the Center, can succeed in their lives. Unfortunately, their mother could not stand the test that befell on her and died in August 2023. Vanya and Misha were informed that their mother had died. Now the guys are left completely alone with their grief and sadness visible in their faces and eyes. But their hope is still with them. Vanya and Misha need a family that can give them love, warmth and care, or good mentors. They attend church every weekend, pray and read the Bible on their own, with volunteers and with some teachers and caregivers. It gives them more faith for a better future and that they will be successful. Thank you all for your prayers and support in our ministry to these guys. Let's continue to take care of them together.</p>
                        <p>Also good and permanent volunteers have appeared in our team over the past 5 years: Danylo Malashko - a student of TNU, received thanks from the mayor of Kyiv Vitali Klitschko for his volunteer work, Andrii Vydrin, Anton Yevtushevsky, Oleksandr Davydenko, Max Tikhonov, Svyatoslav Bondarenko, Varvara Kush, Yevgenia Tereshchenko , Maria Lyaskovska, Sofia Yarova and others. And we want to share with you the story of one of them</p>
                    </div>
                    
                    <PicAndText title={<div className="Ohua-wrap-content-title">
                        <h2>The story of Andrii and OH UA</h2>
                    </div>} text={
                        <div className="Ohua-wrap-content-p">
                            <p>My acquaintance with the Orphan's Hope Ukraine team took place in November 2018 during the first year of study at the Taurida National University. During my first trip to the Center of Social and Psychological Rehabilitation for Children No. 1 in Kyiv “Mayak” I met other volunteers and a lot of teens. At that time, I had just moved to Kyiv and was a rather inexperienced volunteer and that's why I had a hard time finding a common language with the children. But even then, after being trained by the OH UA team, I attended one group of teens every week and realized what my systematic and meaningful attention means a lot even for one kid. And I knew how important it is - to build a trusting relationship with him.</p>
                            <p>After more than a year of valuable and focused volunteer work at the Center, in January 2020, covid-19 pandemia started and prevented my visits to the Center for some time. Also in the February, 24th 2022 war was added to this.</p>
                            <p>In April-May 2023 I realized that there were many children in the Center again and that each of them needed our attention and help. So I continued my work at the Center in the group of middle aged boys. There were 15 of them. The whole orphanage number of kids was 81. </p>
                            <p>After getting to know them better and making an assessment of their needs, we decided to start the "7 Habits of Highly Effective Teenagers" course for them with our OHUA team during summer time and then the "Self Sufficiency Lessons'' course. Also that time we held 2 summer camps and various activities for kids, the “Happy Day" project for the motivation and socialization of children - we visited local McDonald's, KFC, bowling and the cinema together. We also learn to be more experienced and competent volunteers by studying at the Volunteer School throughout the 2023 year.</p>
                            <p>At the Center, in particular, I got to know Zhenya, with whom I have been in constant communication for almost a year and with whom I have built a permanent trust based relationship. I want to tell you his story.</p>
                        </div>
                    } url={andryImg} />
                    <TextAndPic title={<div className="Ohua-wrap-content-title">
                        <h2>Story of Zhenya</h2>
                    </div>} text={
                        <div className="Ohua-wrap-content-p">
                            <p>Zhenya is one of the “Mayak” orphanage 10 years old pupils. His hometown is Zaporizhzhya. </p>
                            <p>Once, during his mother's trip somewhere to another city, Zhenya was at home just with his father. At some point, Zhenya's father became ill and was taken by an ambulance. Zhenya was left alone at home, so had to be taken by the Social Service. This was the first time he got to an orphanage Center in Zaporizhzhya. </p>
                            <p>In spring 2022, Zaporizhzhia and the surrounding area was fired by russian missiles. Zhenya and the rest of the children from the shelter were moved to Kyiv, so that we met him in the middle group of the Center Mayak. </p>
                            <p>Zhenya was one of 12 teens I met during my first visit to Mayak as part of the "Men's Club" volunteer team in the beginning of May 2023. At that time, he had already been in the Center for almost a year. And he visited 4th grade at the public school near the orphanage. </p>
                        </div>
                    } url={jeniaImg} />
                    <div className="Ohua-wrap-content-p">
                        <p>I immediately found a common language with him and learned that he dreamed of becoming a chef, and that his favorite dish is Olivier salad. That is why he is not too much of a fanatic of  McDonald's, like the vast majority of children from the orphanage, but prefers Puzata Hata (the small restaurant of Ukrainian food). He loves to play soccer, attends the section and trains a lot so every visit I invite him to the field to play together. There, he likes to try on any role - from goalkeeper to striker, although his favorite football player is Mbappe from Paris. </p>
                        <p>For the next month in Mayak, I tried to know him better and understood his deeper needs, not only kicking the ball with him on the field. Together we decided to start teaching the middle group of teens the "7 Habits of Highly Effective Teenagers" - a course by Steven Kovi. And Zhenya was one of the most proactive "students" at our course. He works both in our classes and after classes on his own with the book and other boys, so you can always get good feedback from him under each topic. I like him for this habit, he isreally smart. Zhenya is responsible for the tasks assigned to him and carefully fulfills them step by step and he was awarded not just one time, but even some times with our trips to the special Happy Day project for teens to the local community. Zhenya believes in God quite strongly, reads the Bible every day and quotes it to us, and also goes to church every Sunday with volunteers. </p>
                        <p>We became friends with Zhenya and I built quite a strong relationship with him as a volunteer, spent good meaningful time with him and I am grateful for that. However, he wants to come back to his home and family in his native city Zaporizhzhya, as a kid of his parents. We don`t know yet if his dreams will come true, or if we will find a foster family for him, but I sincerely hope that Zhenya will finish his 5th grade good and I will make steps together with him for it. Also I believe that Zhenya will be happy, safe and one of the new generation of Ukrainian people. Thanks for your generous help and support, we can make Zhenya`s dreams come true. </p>
                    </div>
                    <PicAndText title={<div className="Ohua-wrap-content-title">
                        <h2>Our last story is about Stas from Crimea </h2>
                    </div>} text={
                        <div className="Ohua-wrap-content-p">
                            <p>Stas, a pupil of the Mayak Center. He is 14 years old and came from the city of Sevastopol.</p>
                            <p>Stas moved to Kyiv from Crimea when his mother died, and his only relative - his uncle - took custody of the boy.</p>
                            <p>For a while, it seemed that Stas was able to find himself again, although not in his native, but caring family, but unfortunately, this was not the case. A wife of Stas`s uncle, who had her own child, could not get along with the boy, as a result, the man had to choose between his son and his wife and Stas. As you can guess, he did not choose Stas.</p>
                            <p>Thus, in June 2023, Stas was sent to the group of middle aged boys at the Mayak Center, where he immediately made friends with the heroes of our stories: Zhenya, Misha and Vanya, and got a place to sleep with them in the same room.</p>
                            <p>After getting to know him a little better over the summer, I got to know his story, learned that he likes programming in Unity and wants to program or test games in the future. He also plays basketball, does well in school, believes in God, reads the Bible, and tries to go to church every week.</p>
                            <p>In our 7 Habits of Highly Effective Teens classes, robotics, and camps, he shows himself to be a proactive, responsible, and persistent guy. According to the results of the knowledge check of the course, as well as for his active position, Stas was awarded a trip to KFC as part of the Happy Day project in October 2023.</p>
                        </div>
                    } url={stasImg} />
                    <div className="Ohua-wrap-content-p">
                        <p>During this time, Stas and I became cloth friends and spent fun and meaningful time together. But like all children, Stas hopes to find himself in a loving, caring family again. Perhaps Stas's uncle will be able to return to the care of his nephew, although most likely we will have to find him a foster family or a mentor. In any case, the People UA team and I are putting a lot of effort into ensuring that Stas's future is happy, and that he himself lives in safety and well-being.</p>
                    </div>
                    <div className="Ohua-wrap-content-footer">
                        <p><b><i>Sincerely yours, Dmytro Malashko & Orphans Hope UA team Liliya, Pavlo, Daniel & Andrew</i></b></p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default ProjectOhua;